# This is a basic workflow to help you get started with Actions

name: Windows Build & Test

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      
    - name: Restore NuGet packages
      run: msbuild Libraries.sln /p:Configuration=Release /t:Restore
      
    - name: Run MSBuild on solution
      run: msbuild Libraries.sln /p:Configuration=Release

    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1

    - name: Run release build unit tests
      run: dir -r tests/**/*.Tests.dll | where {$_.Directory -like '*\bin\Release\*'}| %{ write-host $_; vstest.console.exe $_ /Platform:X64 }
      
    # Runs a set of commands using the runner's shell
    #- name: Run a multi-line script
    #  run: |
    #   echo Add other actions to build,
    #   echo test, and deploy your project.
